version: '3.1'

services:

  wordpress:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 13001:80
    env_file: .env
    volumes:
      - ./wp-site01/html:/var/www/html

  mariadb:
    image: mariadb:10.5.3-focal
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql