version: '3.1'

services:
  mariadb:
    image: mariadb:10.5.3-focal
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  # ------- WordPress Container(Required) -------
  # wp-first:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 13001:80
  #   env_file: .env-wp-site01
  #   volumes:
  #     - ./wp-site01/html:/var/www/html
  # ---------------------------------------------

  # ------- For Debug ... ------- ↓
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mariadb
  #   links:
  #     - mariadb
  #   ports:
  #     - 13000:80
  #   volumes:
  #     - "./phpmyadmin/sessions:/sessions"