version: '3.1'

services:

  wordpress:
    image: wordpress:php7.2-apache
    restart: unless-stopped
    container_name: wp-container_name
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 13001:80
    env_file: .env
    volumes:
      - ./html:/var/www/html

  mariadb:
    image: mariadb:10.5.3-focal
    restart: unless-stopped
    container_name: wordpress_mariadb
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  mariadb: